# Generated by Django 2.1.1 on 2019-01-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('title', 'type')},
        ),
    ]
