# Generated by Django 2.1.4 on 2019-01-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190107_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_date_on_sale',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_date_on_sale',
            field=models.DateTimeField(null=True),
        ),
    ]
