# Generated by Django 2.1.1 on 2019-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190120_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.TextField(null=True),
        ),
    ]
